package com.thenewjourney.blocks;

import com.cj3636.lib.Ref;
import net.minecraft.block.Block;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.item.Item;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

public class BlockRenderer {
	@SideOnly(Side.CLIENT)
	public static void registerBlockRender() {
	    reg(ModBlocks.AquisOre);
	    reg(ModBlocks.AquisBlock);
	    reg(ModBlocks.Graphite);
	    reg(ModBlocks.CobaltOre);
	    reg(ModBlocks.CobaltBlock);
	    reg(ModBlocks.DistortedOre);
	    reg(ModBlocks.DistortedBlock);
	    reg(ModBlocks.FireOre);
	    reg(ModBlocks.FireBlock);
	    reg(ModBlocks.RubyOre);
	    reg(ModBlocks.RubyBlock);
	    reg(ModBlocks.ShadowOre);
	    reg(ModBlocks.ShadowBlock);
	    reg(ModBlocks.BeeHive);
	    reg(ModBlocks.ArcaneSoil);
	    reg(ModBlocks.BurntStone);
	    reg(ModBlocks.BurntStoneStairs);
	    reg(ModBlocks.Carpet);
	    reg(ModBlocks.Carpet2);
	    reg(ModBlocks.Carpet3);
	    reg(ModBlocks.CarpetG);
	    reg(ModBlocks.CarpetG2);
	    reg(ModBlocks.DistortedStone);
	    reg(ModBlocks.DistortedBricks);
	    reg(ModBlocks.CrypticBlock);
	    reg(ModBlocks.ArmoredStone);
	    reg(ModBlocks.ArmoredGlass);
	    reg(ModBlocks.BurntBricks);
	    reg(ModBlocks.BurntBrickStairs);
	    reg(ModBlocks.WarpStone);
	    reg(ModBlocks.WarpStoneStairs);
	    reg(ModBlocks.Marble);
	    reg(ModBlocks.MarbleStairs);
	    reg(ModBlocks.ClearGlass);
	    reg(ModBlocks.KingBlock);
	    reg(ModBlocks.ObsidianGlass);
		reg(ModBlocks.StoneMan);
		reg(ModBlocks.FireFern);
		reg(ModBlocks.NarcoBush);
		reg(ModBlocks.NarcoBerryBush);
		reg(ModBlocks.Mortar);
		reg(ModBlocks.Weed);
		reg(ModBlocks.FlorusBlock);
	    reg(ModBlocks.Compiler);
	    reg(ModBlocks.CompressedFlorusBlock);
	    reg(ModBlocks.GraniteFurnaceActive);
	    reg(ModBlocks.GraniteFurnaceIdle);
	    reg(ModBlocks.AndesiteFurnaceActive);
	    reg(ModBlocks.AndesiteFurnaceIdle);
	    reg(ModBlocks.DioriteFurnaceActive);
	    reg(ModBlocks.DioriteFurnaceIdle);
	    reg(ModBlocks.NetherrackFurnaceActive);
	    reg(ModBlocks.NetherrackFurnaceIdle);
	    reg(ModBlocks.NetherBrickFurnaceActive);
	    reg(ModBlocks.NetherBrickFurnaceIdle);
	    reg(ModBlocks.BrickFurnaceActive);
	    reg(ModBlocks.BrickFurnaceIdle);
	    reg(ModBlocks.RefractoryBrick);
	    reg(ModBlocks.BlastFurnace);
	    reg(ModBlocks.ArcaneFurnace);
	    reg(ModBlocks.ArcanePillar);
	    reg(ModBlocks.Purifier);
	    reg(ModBlocks.Duplicator);
	    reg(ModBlocks.IngotCast);
	    reg(ModBlocks.BlastFurnaceActive);
	    reg(ModBlocks.VisceonCore);
	    reg(ModBlocks.Substrate);
	    reg(ModBlocks.Crystal);
	    reg(ModBlocks.CrystalProvider);
	    reg(ModBlocks.Provider);
	    reg(ModBlocks.Frame);
	    reg(ModBlocks.Distributor);
	    reg(ModBlocks.Quarry);
	    reg(ModBlocks.Apiary);
        reg(ModBlocks.PervatekiForge);
        reg(ModBlocks.ForgeController);
        reg(ModBlocks.ForgeControllerOn);
        reg(ModBlocks.SentinelSpawn);
        reg(ModBlocks.Lamp);
        reg(ModBlocks.Chandelier);
        reg(ModBlocks.Idol);
        reg(ModBlocks.ImbuedCauldron);
        reg(ModBlocks.GobletBlock);
        reg(ModBlocks.CopperOre);
        reg(ModBlocks.CopperBlock);
        reg(ModBlocks.TinOre);
        reg(ModBlocks.TinBlock);
        reg(ModBlocks.BronzeBlock);
        reg(ModBlocks.PurviaLignumLog);
        reg(ModBlocks.PurviaLignumPlanks);
        reg(ModBlocks.PurviaLeaves);
        reg(ModBlocks.PurviaGrass);
    }
	public static void reg(Block block) {
	    Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(block), 0, new ModelResourceLocation(Ref.MODID + ":" + block.getUnlocalizedName().substring(5), "inventory"));
	}
}
